# Generated by Django 5.1.1 on 2024-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
